---
title: "Trends in Cardiovascular Risk Factors in Canada: Variation by Migration, Temporal, and Socioeconomic Factors, 2000-2018"
csl: vancouver.csl
output:
  word_document: 
    reference_docx: "template.docx"
bibliography: bibliography.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(readr)
library(knitr)
library(kableExtra)
```

**Authors:**

Kitty Y.A. Chen^1,2^, Anan Bader Eddeen^1,3^, Carol Bennett^1^, Warsame Yusuf^4^, Deirdre Hennessey^5^, Joel Barnes^5^, Douglas G. Manuel, MD^1,3,5,6,7,8^

1.  Clinical Epidemiology Program, Ottawa Hospital Research Institute, Ottawa, Ontario, Canada
2.  University of Toronto, Toronto, Ontario, Canada
3.  University of Ottawa, Ottawa, Ontario, Canada
4.  Public Health Agency of Canada, Ottawa, Ontario, Canada
5.  Statistics Canada, Ottawa, Ontario, Canada
6.  Ottawa Hospital Research Institute, Ottawa, Ontario, Canada
7.  Department of Family Medicine, University of Ottawa, Ottawa, Ontario, Canada
8.  School of Epidemiology, Public Health and Preventative Medicine, University of Ottawa, Ottawa, Ontario, Canada
9.  Institute for Clinical Evaluative Sciences, Ottawa and Toronto, Ontario, Canada

**Corresponding author information:**

Kitty Chen

Ottawa Hospital Research Institute - Civic Campus

[kitchen\@ohri.ca](mailto:kitchen@ohri.ca){.email}

**Abstract**

**Background:** The incidence of cardiovascular disease has decreased in Canada; however, it is unclear whether this trend will continued. This national study Canadians described seven cardiovascular disease risk factors risk factors across 18 years, with an examination of patterns across migration status, socioeconomic factors, and time.

**Methods:** 1,065,391 respondents from the Canadian Community Health Surveys (CCHS) from 2000 to 2018 were used to estimate the national trends in health conditions (hypertension, diabetes, high blood cholesterol, and obesity) and health behaviours (smoking, activity levels, and alcohol consumption). The trends were then compared across immigration status.

**Results:** During the study period, Canadian respondents reported an increased prevalence of two or more risk factors across all population groups. The prevalence of self-reported diabetes, hypertension, and obesity increased in Canada. For health behaviour, smoking decreased across all groups, especially in racialized populations. Heavy drinking was most prevalent for non-racialized and non-Indigenous populations Canada-born populations and the lowest for racialized immigrants. Physical inactivity was most prevalent for immigrant populations, especially among established racialized immigrants. However, except for racialized long-term immigrants, the prevalence of self-reported heart disease decreased.

**Conclusions:** Overall, there has been a mixed pattern of risk factor change in Canada since 2000. Established immigrants in Canada (10 or more years since immigrating to Canada) had a higher prevalence of CVD risk factors compared to their native-born counterparts.

**Keywords:** cardiovascular disease, chronic disease, risk factors, Canada, migration, health

**Acknowledgments:** This project is supported by a CANHEART SPOR (www.canheart.ca) summer studentship funded through a Canadian Institutes of Health Research (CIHR) Strategy for Patient Oriented Research (SPOR) Innovative Clinical Trial Multi Year Grant (MYG 151211). Thank you to Rachel Colley and Rochelle Garner for their constructive comments on the manuscript.

**Word count:** Abstract: 195 ; Text body: 3082

**Table and figures:** 7

**What is already known on this subject?**

-   Cardiovascular incidence and mortality in Canada have decreased over several decades due to improved health behaviours and health care.
-   The pattern of cardiovascular risk factors across ethnicity and immigrant groups has not been well established in Canada.

**What does this study add?**

-   Compared to previous studies, this study examined a broader range of risk factors over a longer period of time. There was a mixed pattern in the temporal trend of cardiovascular risk factors in Canada over an 18-year period (2000-2018).
-   Established and racialized immigrants report a higher prevalence of cardiovascular risk factors than non-immigrant Canadians.

\pagebreak

## Background

Currently, immigrants make up more than 20% of Canada's population, and the proportion continues to increase. Certain immigrant groups experience a higher risk of chronic diseases such as cancer, diabetes, and heart disease, which has clinical implications for preventative care and provision of health services to migrant groups in Canada[@gushulakMigrationHealthCanada2011].

Cardiovascular disease (CVD) is the second leading cause of death in Canada[@statisticscanadaLeadingCausesDeath2022]. The incidence and death rate is decreasing[@botlyRecentTrendsHospitalizations2020] with the advancements in heart disease interventions and an improvement in some in behaviour risk factors such as smoking. However, sustained efforts are required to further decrease the prevalence of health disease risk factors[@publichealthagencyofcanadaHeartDiseaseCanada2017]. Behaviours such as smoking, alcohol use, stress, physical activity, and diet are modifiable risk factors for leading chronic diseases including type 2 diabetes, CVD, and cancer[@mudryjRelationshipsHealthrelatedBehaviours2019][@rosellaPopulationRiskBurden2019].

From a population perspective, smoking, followed by high blood pressure, physical inactivity, obesity, diabetes, and poor diet are the most influential risk factors for CVD[@lloyd-jonesDefiningSettingNational2010]. Less is known about migration and major CVD risk factors. With the growing diversity in Canada, a greater understanding of health status and risk factors prevalent in different groups within the population is important to guide contextually appropriate health interventions[@tanuseputroRiskFactorsCardiovascular2003].

Previous studies have described CVD risk factors and their association with socioeconomic status over two time periods: 1994-2005[@leeTrendsRiskFactors2009][@tanuseputroRiskFactorsCardiovascular2003] and 2005-2016[@daiTrendsRegionalVariation2021]. In this study, national trends in heart disease and a wide range of risk factors related to CVD were examined among the Canadian population aged 12 years or older using the Canadian Community Health Survey (CCHS) over an 18-year period from 2001 to 2018.

## Data and methods

### Study data

The Canadian Community Health Survey (CCHS) is a cross-sectional survey that collects information related to health status, health determinants, and socio-demographic characteristics for the Canadian household population aged 12 years and up. The survey covers the ten provinces and the three territories, excluding persons living on First Nations reserves and settlements, full-time members of the Canadian Forces, and institutionalized persons. Data collection was conducted over the phone or in-person, and the data was collected directly from the respondents using computer-assisted personal and telephone interview software. The interview can be conducted in English or French. Each Statistics Canada Regional Office recruited interviewers with a variety of language competencies to remove language barriers. Detailed information about the CCHS is available online[@statisticscanadaCanadianCommunityHealth2021].

To reflect improved survey methodology, the CCHS has updates and changes each cycle with a major update in 2015. In 2015 redesign , a new collection strategy was implemented with a new sample frame and modernized content. More information about the redesign is available online [@statisticscanada2007][@statisticscanadaCanadianCommunityHealth2015].

### Ascertainment of risk factors and immigrant status

The current analysis focused on cardiovascular disease and seven risk factors, derived from the CCHS. The health behaviours are characterized in Table 1. Heart disease and related risk factors are based on self-report [@leeTrendsRiskFactors2009]. Ascertainment of risk factors was generally consistent between cycles, but changes to question wording did occur. There are more notable changes in the CCHS design and the survey questionnaire in 2015. The *cchsflow* R package was used to harmonize the ascertainment of risk factor exposure across CCHS survey data between 2000 to 2018 such that the same variable type was renamed as a common variable name[@yusufCchsflowOpenScience2021]. In addition to the CCHS variables, there were also derived variables from *cchsflow*, such as binge drinking that was not available in the original CCHS PUMF.

This study focused on cardiovascular disease and seven risk factors, derived from the CCHS. The health behaviours are characterized in Table 1. Heart disease was defined as any condition that affects the heart and blood vessels. Heart disease and related risk factors are based on self-report [@leeTrendsRiskFactors2009].

Ascertainment of risk factors was generally consistent between cycles, but changes to question wording did occur. There are more notable changes in the CCHS design and the survey questionnaire in 2015. The greatest changes occurred for the ascertainment of physical activity (see below).

Details of how all risk factors where ascertained are described in the *cchsflow* R package that was used to harmonize the ascertainment of risk factor exposure across CCHS survey data between 2000 to 2018[@yusufCchsflowOpenScience2021]. In addition to the original CCHS variables, binge drinking (list any other variable) were derived from existing risk factor questions. These are also described in the *cchsflow* library.

**Table 1**: Risk factor definitions with categories are marked with (\*).

Physical inactivity was defined as leisure time physical activity less than 1.5 MET-hours/day [@jetteMetabolicEquivalentsMETS1990]. Prior to 2015, activity level of respondents was derived from an aggregate list of self-reported leisure-time physical activities related to frequency and duration of activity[@manuelMeasuringBurdenUnhealthy2016]. Respondent's average daily energy expenditure during leisure-time physical activity was calculated as the sum of the frequency and duration of the physical activity and the MET value of each activity. From 2015 onward, activity level was separated by age group: 12-17 years old and 18+ years old. Using the volume of weekly activity variable (PAADVVOL), a derived variable was created by removing the active transportation in the new function to align with previous survey cycles [@CchsflowPhysicalActivity2022].

Patients with hypertension were those who have received a diagnosis for this condition from a physician, irrespective of antihypertensive treatment. Respondents with diabetes were defined as patients who have received a diagnosis of diabetes from a physician, regardless of whether they are receiving treatment with insulin or oral hypoglycemic medications. Respondents who had diabetes during pregnancy were defined as not having diabetes. Body mass index (BMI) was derived from the respondent's self-reported height divided by the square of their self-reported height. Obesity was defined as BMI greater than equal to 30[@akilRelationshipsObesityCardiovascular2011]. Smoking was based on the respondent's past year smoking status (current, former, and never).

The respondents were stratified by sex and age groups (12-34, 35-49, 50-64, 65-74, and ≥ 75 years), following the age groups of the previous analyses[@leeTrendsRiskFactors2009]. Six immigration groups were generated: non-racialized and non-Indigenous populations Canada-born, non-racialized and non-Indigenous populations recent immigrant, non-racialized and non-Indigenous populations established immigrant, racialized Canada-born, racialized recent immigrant, and racialized established immigrant. Recent immigrants refer to immigrants who have resided in Canada for up to 9 years, whereas established immigrants refer to those in Canada for 10 years or more.

Hypertension was defined as respondents who reported received a diagnosis for this condition from a physician, irrespective of anti-hypertensive treatment.

Diabetes was defined as patients who have received a diagnosis of diabetes from a physician, regardless of whether they are receiving treatment with insulin or oral hypoglycemic medications. Respondents who had diabetes during pregnancy were defined as not having diabetes.

Body mass index (BMI) was derived from the respondent's self-reported height divided by the square of their self-reported height. Obesity was defined as BMI greater than equal to 30[@akilRelationshipsObesityCardiovascular2011].

Smoking was based on the respondent's past year smoking status (current, former, and never).

The respondents were stratified by sex and age groups (12-34, 35-49, 50-64, 65-74, and ≥ 75 years), following the age groups of the previous analyses[@leeTrendsRiskFactors2009]. Six immigration groups were generated: non-racialized and non-Indigenous populations Canada-born, non-racialized and non-Indigenous populations recent immigrant, non-racialized and non-Indigenous populations established immigrant, racialized Canada-born, racialized recent immigrant, and racialized established immigrant. Recent immigrants refer to immigrants who have resided in Canada for up to 9 years, whereas established immigrants refer to those in Canada for 10 years or more.

### Regional variations

The prevalence of each risk factor was determined across all provinces and territories in Canada.

### Statistical analysis

> The prevalence and trends of each risk factor were analyzed from 2000 to 2018, adjusting for survey sampling weights, and evaluated using linear regression analysis. Using the pooled approach, sampling weights from the combined PUMFs are bootstrapped to assess the variance of estimates. All analysis was conducted using R 4.0 and can be found on {link to GitHub repository}. The data used in the study are openly available under the Statistic Canada open license {link to GitHub repository - folder with data}[@statisticscanadaStatisticsCanadaOpen].

The prevalence of the risk factors was directly standardized for age and sex, using the 2011 Canadian Census population. The time trends in risk factors were stratified by migrant group categories. The relative change from 2000 to 2018 for each risk factor was determined by calculating the percent change in the last year of the study period and the baseline prevalence in 2001.

Statistical uncertainty for prevalence estimates and other measures were calculated using survey bootstrap weights for 2015 onward using the survey R package. Prior to 2015, bootstrap weights were not available; and, therefore, no bootstrap weights were used for this period. To compare the two approaches, statistical uncertainty was calculated with and without bootstrap weights for 2015 onward. Regression beta coefficients with p-values less than 0.05 were considered statistically significant.

## Results

### Study data

The distribution of the study sample by sex from all cycles is described in Table 2. In 2001, the largest age group was 12-34 years old (35%), with 49% males. In 2017, the largest age group was also 12-34 years old (37%), with 51% males. The largest group was non-racialized and non-Indigenous populations Canada born (72%), followed by racialized immigrants (10+ years in Canada) with 8.4%, non-racialized and non-Indigenous populations immigrants (10+ years in Canada) with 7.8%, racialized Canada-born with 6%, racialized immigrants (0-9 years in Canada) with 4.8%, and non-racialized and non-Indigenous populations immigrants (0-9 years in Canada with 1.3%. Approximately 70% of the study sample has at least one of the following risk factors.

> The racialized Canada-born and non-racialized and non-Indigenous immigrant groups increased in proportion of the total population until 2015, when there was a decrease in 70% and 31% from the 2013 survey, respectively. See appendix X.

**Table 2**: Baseline characteristics of unweighted and weighted total CCHS population from 2000 to 2018, stratified by sex.

### Heart disease

In 2017, 4.87% (1.38 million) of the Canadian population reported heart disease. The prevalence of self-reported heart disease decreased over the 2000-2018 period. In 2001, the age-sex standardized Canadian prevalence for females and males was 4.95% and 5.67%, respectively 1.25 million and 1.43 million. In 2017, the national prevalence of heart disease in females was 4.16% (1.18 million), and in males with 5.62% (1.59 million), indicating a relative decrease of 0.87% for females and 15.95% for males. The decrease in heart disease rates was also apparent in immigrant groups except for racialized immigrants (10+ years in Canada) with a 20% increase (Figure 1). Compared to 2001, the prevalence of heart disease in 2017 decreased by 35% in racialized Canada-born, 1% in non-racialized and non-Indigenous populations Canada-born, 22% in racialized immigrants (0-9 years in Canada), 42% in non-racialized and non-Indigenous populations immigrants (0-9 years in Canada), and 12% in non-racialized and non-Indigenous populations immigrants (10+ years in Canada).

**Figure 1**: Age- and sex-adjusted trends in heart disease from 2000 to 2018, stratified by migrant groups.

### Trends in risk factors

National risk factor trends by sex and age group are presented in Table 3. Approximately 70% of the study sample has at least one of the following risk factors: hypertension, diabetes, obesity, physical inactivity, current smoker, heavy drinker or high blood cholesterol.

**Table 3**: Age- and sex-adjusted prevalence of risk factors for survey respondents aged 12 years and older, from 2000 to 2018.

**Table 4**: Prevalence of risk factors, by age categories, from 2000 to 2018.

### Trends in risk factors by migrant group

Both non-racialized and non-Indigenous populations and racialized immigrants (10+ years in Canada) had a higher prevalence of CVD risk factors than Canada-born populations; however, their time trends are similar to non-racialized and non-Indigenous populations Canada-born populations (Figure 2). The trends were similar for hypertension, diabetes, high blood cholesterol, and physical inactivity. The prevalence of heavy drinking was lowest among racialized immigrants and highest among non-racialized and non-Indigenous populations Canada-born respondents. Current smokers were decreasing across all groups with the largest decrease in 2015, where racialized populations had the lowest prevalence. The prevalence of physical inactivity was higher in immigrants than in Canada-born populations, especially with racialized immigrants with a prevalence greater than 50%. Hypertension, obesity, and diabetes continued to increase in all population groups. Obesity was greatest among non-racialized and non-Indigenous populations Canada-born and non-racialized and non-Indigenous populations immigrants (10+ years in Canada), and in 2017, the lowest prevalence was observed among immigrants (0-9 years in Canada). Across all risk factors, non-racialized and non-Indigenous populations Canada-born populations had a higher prevalence compared to racialized Canada-born populations. Having two or more risk factors increased in all population groups.

**Figure 2**: Age- and sex-adjusted prevalence of hypertension, diabetes, obesity, physical inactivity, current smokers, heavy drinkers, and high blood cholesterol from 2000 to 2018, stratified by migrant groups.

### Regional trends

Diabetes doubled in prevalence in all provinces and territories (Table 5). Diabetes was most prevalent in New Brunswick, with a 103% increase (p \< 0.01). Although Yukon, Northwestern Territories (NWT), and Nunavut had the lowest prevalence of diabetes and hypertension, they also had the greatest increase in prevalence of diabetes by 165% (p = 0.44) from 2000 to 2018, and hypertension with 77% (p = 0.02). Hypertension was most prevalent in New Brunswick, Newfoundland and Labrador, and Nova Scotia, with the greatest increase in New Brunswick (62%, p \< 0.01). Obesity was most prevalent in Newfoundland and Labrador, New Brunswick, and Yukon/NWT/Nunavut. The greatest increase in obesity prevalence occurred in Quebec (53%, p = 0.1). Physical inactivity has decreased in all provinces and territories from 2000 to 2018. Current smokers were the most prevalent in Yukon/NWT/Nunavut in 2001 with the greatest difference of -59%. From 2001 to 2015, heavy drinking was least prevalent in Prince Edward Island but had the greatest difference of 59% (p = 0.03). The percent difference in the prevalence of heavy alcohol consumption is calculated from 2001 to 2015. The missing prevalence across certain cycles is attributed to the skip patterns for certain provinces and territories. High blood cholesterol was prevalent in Newfoundland and Labrador (20%), New Brunswick (15%), Nova Scotia (15%), and Ontario (13%) for the 2017-2018 cycle. The greatest difference from 2015-2018 was Prince Edward Island with approximately -19% (p = 0.02).

**Table 5**: Prevalence of risk factors, by provinces and territories in Canada, from 2000 to 2018.

## Interpretation

This national study of over 1 million Canadians described seven cardiovascular risk factors across 18 years. Canadian-born and immigrant respondents by immigrant status, duration in Canada, country of birth and ethnicity were examined. Between 2000 to 2018, there was a mixed pattern where some risk factors decreased, while other risk factors increased. Self-reported prevalence of heart disease was highest among established immigrants in Canada.

Rates of diabetes, obesity and hypertension steadily increased over the study period. Compared to 1994-2005, the rate of diabetes and obesity was higher, with approximately 1.5 times increase over the study period[@leeTrendsRiskFactors2009]. The increasing prevalence of hypertension, diabetes, and obesity followed the increasing trend of previous decades[@tanuseputroRiskFactorsCardiovascular2003][@leeTrendsRiskFactors2009][@daiTrendsRegionalVariation2021]. Of the risk factors, high blood pressure is one of the strongest risk factors for the development of CVD[@fuchsHighBloodPressure2020].

Among individual CVD risk factors, smoking is an independent risk factor in the working-age population. Cessation of smoking in this age group can reduce the calculated risk of CVD to the same extent as non-smokers[@ketoCardiovascularDiseaseRisk2016]. While there is some evidence to suggest that healthy consumption of alcohol may be protective against CVD, heavy alcohol consumption has been associated with an increased risk of CVD and hypertension among older men[@snowAlcoholUseCardiovascular2009]. Increased alcohol consumption is also positively associated with higher levels of high-density lipoprotein cholesterol and higher blood pressure[@larssonAlcoholConsumptionCardiovascular2020]. Physical inactivity is a well-established risk factor for CVD. Physical inactivity was the most prevalent of all CVD risk factors. Previous studies have established that physical activity is associated with a 40-50% reduction of risk in CVD, independent of blood pressure and other known cardiovascular risk factors[@wannametheePhysicalActivityPrevention2001]. Encouragingly, there was a small decline in physical inactivity, which corroborates the fitness trends found in the Canadian Health Measures Survey (CHMS) from 2007 to 2017 [@doyonTrendsPhysicalFitness2021]. The CHMS is a smaller national survey of Canadians that collects physical measures, including blood tests and blood pressure measurements. Physical activity in the CHMS is measured using accelerometers, as well as self-reported measures.

The overall decrease in heavy alcohol consumption, heavy smoking, physical activity, and high blood cholesterol comes with variations in age groups. For example, the proportion of high blood cholesterol is significantly higher in older populations. Hypertension increased more slowly in younger respondents. In general, age-specific trends that were observed in the CCHS correspond to the results of the same physical measures that were reported in the CHMS from 2016 to 2019[@statisticscanadaCholesterolLevelsAdults2021]. Although heart disease has decreased across the study period, the increasing burden of diabetes, obesity and hypertension may result in future increases in CVD. This study did not examine the effect of changing risk factors on the future cardiovascular disease but these effects can be assessed in simulation models, such as the Population Health Model (POHEM)[@hennessyPopulationHealthModel2015][@manuelProjectionsPreventableRisks2014].

In this study, immigrants had a higher prevalence of inactivity than their Canadian counterparts, which corroborates with previous studies[@bryanPhysicalActivityEthnicity2006]. This difference has been attributed to socioeconomic status, employment, and social norms towards physical activity. In addition, the cost associated with certain activities can be an additional deterrent to adopting an active lifestyle[@prattEconomicInterventionsPromote2004][@dograVariationModePhysical2010][@dawsonInfluenceEthnicityLength2005]. Specifically, racialized/visible minority immigrants have a higher prevalence of physical inactivity. A large majority of incoming migrants that identify as a visible minority immigrate from countries in Asia/South Asia. As a result, this may translate to a higher prevalence of physical inactivity at a population level[@mahmoodLeisureTimePhysical2019]. Established migrants report a higher prevalence of risk factors compared to Canada-born respondents, supporting the healthy immigrant effect.

The healthy immigrant effect describes how the recent immigrants report better health than the non-immigrant populations. Still, their health status declines to the same level as their Canada-born counterparts[@aliRecentResearchImmigrant2004][@perezHealthStatusHealth2002]. Consistent with previous studies in Westernized cultures, established immigrants who have settled in the United States for 15 years or longer were more likely to report smoking, obesity, and high blood cholesterol than immigrants who resided in the United States for less than 10 years[@koyaAssociationLengthResidence2007][@chiuCardiovascularRiskFactor2012]. The prevalence of obesity, hypertension, and smoking increased with time since immigration to the United States[@chiuCardiovascularRiskFactor2012][@singhEthnicImmigrantDifferentialsHealth2002]. With Ontario-landed immigrant data, longer-term residents had a significantly higher risk of diabetes than recent immigrants[@creatoreAgeSexrelatedPrevalence2010a]. Therefore, the uneven distribution of national CVD risk factors trends may have significant health implications on recent and established immigrants.

### Limitations

Despite the large representative sample, the study poses some limitations. CCHS relies on self-report data, resulting in the potential underestimation of risk factors and recall bias. Physical activity items only measure leisure physical activity and do not account for active transportation (such as walking and biking to work), work activity, or sedentary time. The leisure physical activity may not be sufficient in accurately portraying the complete effect of physical activity on each subgroup. In surveys, respondents tend to over-report their healthy behaviours and underreport their unhealthy behaviours. This is referred to as "social desirability bias". For example, self-reported alcohol consumption in surveys accounts for half the volume of alcohol sold[@manuelBurdenHealthBehaviours2019]. Self-reported measures of high blood pressure and cholesterol are subject to reporting bias because not all Canadians have these measures taken or know when they are taken. That stated, there was a general alignment between self-reported measures in the CCHS and the CHMS. A strength of the CCHS compared to the CHMS is the large sample size of the CCHS, which allows the examination of subgroups.

In terms of the information related to immigrants, the information related to country of origin is limited in the PUMF with only one survey question asking if their country of origin is Canada or outside of Canada. Ethnicity is dichotomously categorized into 'non-racialized and non-Indigenous populations' and 'racialized' in the PUMF. More detailed ethnicity is recorded in the CCHS and can be assessed with permission at Statistics Canada's Regional Data Centres.

Health behaviours can vary by country of origin and ethnicity because of cultural norms and customs. Because of the differences in place of origin and ethnicity, health differences observed among immigrant groups may be due to a cohort effect, where established immigrants may have had worse cardiovascular risk profiles before immigrating to Canada[@perezHealthStatusHealth2002]. Previous studies using longitudinal data provide evidence to validate our findings[@ngDynamicsImmigrantsHealth2005]. As a next step, it is feasible to link immigration data related to the country of origin, settlement time, and ethnicity for a more robust assessment of CVD risk factors in immigrants. Further investigations into the immigrant subgroups such as protected persons, economic immigrants, and humanitarian immigrants will detail further context into the health behaviours from different circumstances. Cohort analysis by place of origin and more detailed ethnic groups can be used to identify at-risk immigrant cohorts.

### Conclusion

The current study highlights the distributions and trends of CVD risk factors among Canadians and Canada's migrant population from 2000 to 2018. With encouraging trends such as decreased smoking and physical inactivity, the increasing prevalence of obesity, diabetes, and hypertension is still of concern. The varying trends are further divided by provincial and territorial differences. The substantial variations in CVD risk factors among immigrant groups may have serious implications for established cardiovascular health. This is especially evident in established immigrants in Canada. A focus on CVD risk factor management along with equitable access to health care services could prevent many cardiovascular events. The shift in migration pattern necessitates considering migration and geographical factors for support and services. Such approaches can reduce the burden of CVD and their inequalities among migrant groups.

\pagebreak

## References

::: {#refs}
:::

\pagebreak
