---
title: "Cardiovascular risk health factors and disease among Canadian Immigrants"
output: word_document
author: "Kitty Chen^[1] and Douglas G Manuel^[1,2,3,4,5,6,7] "
fontsize: 12pt

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

1. Clinical Epidemiology Program, Ottawa Hospital Research Institute 
2. Department of Family Medicine, University of Ottawa 
3. School of Epidemiology and Public Health, University of Ottawa 
4. Institute for Clinical Evaluative Sciences 
5. Statistics Canada 
6. C.T. Lamont Primary Health Care Research Centre and Brüyere Research Institute 
7. Dalla Lana School of Public Health, University of Toronto


**Background:** The intersection of immigration and heart health is complex, especially because of the variation within the growing immigrant population with respect to education, income, and socio-economic position. With the recent advancements in heart disease interventions and prevention in the past few decades, sustained efforts are required to further decrease the development of health disease risk factors. Many risk factors related to cardiovascular disease and stroke can be prevented by changes in daily life and in health policy. In recognizing the prevalence in risk factors across sexes, different age groups, ethnic groups, and broad geographical regions, health professionals and program planners can focus their efforts on specific at-risk groups of the population.

**Objective:** To examine national trends in heart disease and risk factors related to cardiovascular disease from 2001 to 2018. 

**Methods:** Canadian Community Health Survey (CCHS) is a cross-sectional survey that collects information related to health status, health determinants, and socio-demographic characteristics for non-institutionalized Canadian household population aged 12 and up. Using CCHS, it is of interest to know how risk factors such as hypertension, diabetes, smoking, activity levels, and obesity can influence cardiovascular disease in different regions in Canada, as well as to see how the prevalence of each factor has changed over time from 2001 to 2018. The prevalence of the risk factors will be adjusted for age and sex, and the relative change from 2001 to 2018 for each risk factor will be determined. The prevalence of the risk factors will then be stratified by provinces, and immigration status.

**Results:** During the study period, the prevalence of diabetes, hypertension and obesity increased for all groups in Canada. Trends in diabetes, hypertension and obesity were consistent for all provinces. We expect to see significant variations in the burden of cardiovascular risk factors among immigrant and native-born populations. 

**Conclusion:** During the study period, the prevalence of diabetes, hypertension and obesity increased for all groups in Canada. Trends in diabetes, hypertension and obesity were consistent for all provinces. We expect to see significant variations in the burden of cardiovascular risk factors among immigrant and native-born populations. 


