---
title: "table-1a"
author: Kitty Chen
date: 2021-10-26
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Table 1a analysis

```{r Factoring each variable, message=FALSE, warning=FALSE, include=FALSE}
library(dplyr)

T1 <- harmonized_combined

# Sex
T1$DHH_SEX <-
  factor(T1$DHH_SEX, levels=c(1,2),
         labels=c('Male','Female'))
levels(T1$DHH_SEX)

# Province
T1$Province <- as.factor(T1$Province)
levels(T1$Province)

# Immigrant group
T1$immigration_der<- 
  factor(T1$immigration_der, levels = c(1:6),
         labels=c('White Canada-born','Non-white Canada-born','White immigrant born outside of Canada (0-9 years in Canada)','Non-white immigrant born outside of Canada (0-9 years in Canada)','White immigrant born outside of Canada (10+ years in Canada)','Non-white immigrant born outside of Canada (10+ years in Canada)'))
levels(T1$immigration_der)

# BMI
T1$HWTGBMI_der_cat4<- 
  factor(T1$HWTGBMI_der_cat4, levels = c(1:4),
         labels=c('Underweight','Normal weight','Overweight','Obese'))
levels(T1$HWTGBMI_der_cat4)

# Hypertension
T1$CCC_071 <-
  factor(T1$CCC_071, levels=c(1,2),
         labels=c('Hypertension','No hypertension'))
levels(T1$CCC_071)

# Diabetes
T1$CCC_101 <-
  factor(T1$CCC_101, levels=c(1,2),
         labels=c('Diabetes','No diabetes'))
levels(T1$CCC_101)

# Blood cholesterol
T1$CCC_075 <-
  factor(T1$CCC_075, levels=c(1,2),
         labels=c('High blood cholesterol','No high blood cholesterol'))
levels(T1$CCC_075)

# Drinking
T1$low_drink_score <-
  factor(T1$low_drink_score, levels=c(1:4),
         labels=c('Low risk', 'Marginal', 'Medium risk','High risk'))
levels(T1$low_drink_score)

# Smoking
T1$SMKDSTY_cat3 <-
  factor(T1$SMKDSTY_cat3, levels=c(1:3),
         labels=c('Current smoker', 'Former smoker', 'Never smoked'))
levels(T1$SMKDSTY_cat3)

# Activity
T1$activity <- as.factor(T1$activity)
levels(T1$activity)

# Year
T1$year <- as.factor(T1$year)
levels(T1$year)

# Province
T1$Province <- as.factor(T1$Province)
levels(T1$Province)
```

```{r Rename titles}
T1 <- T1 %>%
  select(DHHGAGE_cont, DHH_SEX,Province,immigration_der,HWTGBMI_der_cat4,CCC_071,CCC_075,
         CCC_101,low_drink_score,SMKDSTY_cat3,activity, year, WTS_M) %>%
  rename('Age'=DHHGAGE_cont,'Sex'=DHH_SEX, 'Immigration'=immigration_der, 'Body Mass Index (BMI)'=HWTGBMI_der_cat4,
         'Leisure activity'=activity,'Hypertension'=CCC_071,'Blood cholesterol'=CCC_075,
         'Diabetes'=CCC_101,'Low-risk drinking score'=low_drink_score,'Smoking status'=SMKDSTY_cat3, "Year"=year)
colnames(T1)
```

 
```{r Table 1}
library(tableone)
myVars <- c('Sex', 'Immigration', 'Body Mass Index (BMI)',
         'Leisure activity','Hypertension','Blood cholesterol',
         'Diabetes','Low-risk drinking score','Smoking status')
tableOne<- CreateTableOne(vars=myVars,data=T1)
tb1<- print(tableOne)
# write.csv(t,"TableOne1.csv")

```

```{r Table 1 stratified by sex}
library(tableone)
myVars_sex <- c('Immigration', 'Body Mass Index (BMI)',
         'Leisure activity','Hypertension','Blood cholesterol',
         'Diabetes','Low-risk drinking score','Smoking status')
tableOne_sex<- CreateTableOne(vars=myVars_sex, strata='Sex',data=T1)
tb1_sex<- print(tableOne_sex)
# write.csv(tb1_sex,"TableOne_sex.csv")
```

```{r Table 1 stratified by sex (weight and unweighted)}
myVars_sex <- c('Year','Province','Age','Immigration', 'Body Mass Index (BMI)',
         'Leisure activity','Hypertension','Blood cholesterol',
         'Diabetes','Low-risk drinking score','Smoking status','Sex')
t1_unweighted <- gtsummary::tbl_summary(data=T1, by='Sex',
                                         missing = "no")
t1_design <- survey::svydesign(id=~0, weights=~WTS_M, data=T1)
t1_weighted <-gtsummary::tbl_svysummary(data =t1_design, by = 'Sex',
                                        missing = "no")
t1_sex<-gtsummary::tbl_merge(tbls = list(t1_unweighted, t1_weighted),
          tab_spanner=c("**Unweighted**","**Weighted**"))
m<-print(t1_sex)
```

