---
title: "3-Risk-factor-plots"
author: "Kitty Chen"
date: "27/10/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggplot2)
library(dplyr)
library(cchsflow)
library(plotly)
library(srvyr)
library(survey)

plot_data <- harmonized_combined %>%
  select(year,Province, DHH_SEX, Age_Group, CCC_071,CCC_101,CCC_075,activity,HWTGBMI_der_cat4,
         Immigration,Alcohol,SMKDSTY_cat3,Risk_factor,WTS_M)

svy_plot <- as_survey_design(.data=plot_data, weights="WTS_M")

#2011 census population standardization (age and sex)
pop2011 <- c(4962765,3524640,3459035,1281440,917340,4910365,3649325,3593270,1393345,1352950)

## Weighted population by year and immigration
pop_weight <- plot_data %>%
  select(year, Immigration, WTS_M)%>%
  group_by(year, Immigration)%>%
  summarise(Weighted_pop=sum(WTS_M))

```

```{r}
prev_plot <- function(design, sum_var, filter_value, stdpop, startyear, title){
  
  # Prevalence 
  table <- svystandardize(design,by = ~Age_Group+DHH_SEX, population = stdpop)%>%
    group_by(year,Immigration, {{sum_var}}) %>%
    summarise(Prevalence = survey_mean()*100) %>%
    filter({{sum_var}} == filter_value) %>%
    select(-Prevalence_se, -{{sum_var}})
  
  # Plot
  plot <- ggplot(table, aes(x=year, y=Prevalence))+
  geom_line(aes(colour=Immigration))+
  geom_point(aes(colour=Immigration)) +
  ylab("Prevalence (%)")+
  xlab("Year")+
  ggtitle(title)+
  labs(colours="Migration Groups")+
  theme(plot.title = element_text(hjust = 0.5),
        # legend.position = "none", 
        # panel.grid.major = element_blank(),
        # panel.grid.minor = element_blank(),
        # panel.background = element_blank(),
        axis.line = element_line(colour = "black"),
        panel.border = element_rect(colour = "black", fill=NA))+
  scale_x_discrete(limits=c(2001,2005,2009,2013,2017))+ 
  scale_color_brewer(palette = "Paired")
  
  return(plot)
}
```


```{r Hypertension}
ht_plot <-prev_plot(svy_plot, CCC_071, 1, pop2011, 2001, "Hypertension")
ggplotly(ht_plot)
```

```{r Diabetes}
db_plot <-prev_plot(svy_design, CCC_101, 1, pop2011, 2001, "Diabetes")
ggplotly(db_plot)
```

```{r Blood cholesterol}
bc_plot <-prev_plot(svy_design, CCC_075, 1, pop2011, 2015, "High blood cholesterol")
ggplotly(bc_plot)
```

```{r Obesity}
bmi_plot <-prev_plot(svy_design, HWTGBMI_der_cat4, 4, pop2011, 2001, "Obesity")
ggplotly(bmi_plot)
```

```{r Physical inactivity}
mets_plot <- prev_plot(svy_design, activity, "Inactive", pop2011, 2001, "Physical inactivity")
ggplotly(mets_plot)
```

```{r Smoking}
smoke_plot <- prev_plot(svy_design, SMKDSTY_cat3, 1, pop2011, 2001, "Current smoker")
ggplotly(smoke_plot)
```

```{r Drinking}
alc_plot <-prev_plot(svy_design, Alcohol, 4, pop2011, 2001, "Alcohol")
ggplotly(alc_plot)
```

```{r Heart disease}
hd_plot <-prev_plot(svy_design, CCC_121, 1, pop2011, 2001, "Heart disease")
ggplotly(hd_plot)
```



```{r Tables}
## Hypertension (CCC_075 ==1)
ht_year <- plot_data %>%
  filter(CCC_071 ==1)%>%
  select(year, Immigration, CCC_071, WTS_M) %>%
  group_by(year, Immigration)%>%
  summarise(Total=n(),Weight=sum(WTS_M))
ht_year$Prevalence<-ht_year$Weight/pop_weight$Weighted_pop*100

## Diabetes (CCC_101 ==1)
diabetes_year <- plot_data %>%
  filter(CCC_101 ==1)%>%
  select(year, Immigration, CCC_101, WTS_M) %>%
  group_by(year, Immigration)%>%
  summarise(Total=n(),Weight=sum(WTS_M))
diabetes_year$Prevalence<-diabetes_year$Weight/pop_weight$Weighted_pop*100

## Blood cholesterol
bc_year <- plot_data %>%
  filter(CCC_075 ==1)%>%
  select(year, Immigration, CCC_075, WTS_M) %>%
  group_by(year, Immigration)%>%
  summarise(Total=n(),Weight=sum(WTS_M))

# 2015-2017 weights only
pop_weight2015_2017 <-pop_weight %>%
  filter(year %in% c(2015:2017))

bc_year$Prevalence<-bc_year$Weight/pop_weight2015_2017$Weighted_pop*100


## BMI 
bmi_year <- plot_data %>%
  filter(HWTGBMI_der_cat4 %in% c(3:4))%>%
  select(year, Immigration, HWTGBMI_der_cat4, WTS_M) %>%
  group_by(year, Immigration)%>%
  summarise(Total=n(),Weight=sum(WTS_M))
bmi_year$Prevalence<-bmi_year$Weight/pop_weight$Weighted_pop*100

## Drinking
alc_year <- plot_data %>%
  filter(Alcohol %in% c(4:5))%>%
  select(year, Immigration, Alcohol, WTS_M) %>%
  group_by(year, Immigration)%>%
  summarise(Total=n(),Weight=sum(WTS_M))
alc_year$Prevalence<-alc_year$Weight/pop_weight$Weighted_pop*100

## Smoking
smoke_year <- plot_data %>%
  filter(SMKDSTY_cat3 == 1)%>%
  select(year, Immigration, SMKDSTY_cat3, WTS_M) %>%
  group_by(year, Immigration)%>%
  summarise(Total=n(),Weight=sum(WTS_M))
smoke_year$Prevalence<-smoke_year$Weight/pop_weight$Weighted_pop*100

## Activity
activity_year <- plot_data %>%
  filter(activity == "Inactive")%>%
  select(year, Immigration, activity, WTS_M) %>%
  group_by(year, Immigration)%>%
  summarise(Total=n(),Weight=sum(WTS_M))
activity_year$Prevalence<-activity_year$Weight/pop_weight$Weighted_pop*100

## 2+ risk factors
rf_year <- plot_data %>%
  filter(Risk_factor >= 2)%>%
  select(year, Immigration, Risk_factor, WTS_M) %>%
  group_by(year, Immigration)%>%
  summarise(Total=n(),Weight=sum(WTS_M))
rf_year$Prevalence<-rf_year$Weight/pop_weight$Weighted_pop*100

## Heart disease
hd_year <- plot_data %>%
  filter(CCC_101 == 1)%>%
  select(year, Immigration, CCC_101, WTS_M) %>%
  group_by(year, Immigration)%>%
  summarise(Total=n(),Weight=sum(WTS_M))
hd_year$Prevalence<-hd_year$Weight/pop_weight$Weighted_pop*100


```

```{r Plots}
plot_ht <- ggplot(ht_year, aes(x=year, y=Prevalence,))+
  geom_line(aes(colour=Immigration))+
  geom_point(aes(colour=Immigration)) +
  ylab("Prevalence (%)")+
  xlab("Year")+
  ggtitle("Hypertension")+
  labs(colours="Immigration Groups")+
  theme(plot.title = element_text(hjust = 0.5),
        # legend.position = "none", 
        # panel.grid.major = element_blank(),
        # panel.grid.minor = element_blank(),
        # panel.background = element_blank(),
        axis.line = element_line(colour = "black"),
        panel.border = element_rect(colour = "black", fill=NA))+
  scale_x_discrete(limits=c(2001,2005,2009,2013,2017))+ 
  scale_color_brewer(palette = "Paired")

plot_diabetes <- ggplot(diabetes_year, aes(x=year, y=Prevalence))+
  geom_line(aes(colour=Immigration))+
  geom_point(aes(colour=Immigration)) +
  ylab("Prevalence (%)")+
  xlab("Year")+
  ggtitle("Diabetes")+
  labs(colours="Immigration Groups")+
  theme(plot.title = element_text(hjust = 0.5),
        # legend.position = "none", 
        # panel.grid.major = element_blank(),
        # panel.grid.minor = element_blank(),
        # panel.background = element_blank(),
        axis.line = element_line(colour = "black"),
        panel.border = element_rect(colour = "black", fill=NA))+
  scale_x_discrete(limits=c(2001,2005,2009,2013,2017))+ 
  scale_color_brewer(palette = "Paired")

plot_bc <- ggplot(bc_year, aes(x=year, y=Prevalence))+
  geom_line(aes(colour=Immigration))+
  geom_point(aes(colour=Immigration)) +
  ylab("Prevalence (%)")+
  ggtitle("High blood cholesterol")+
  xlab("Year")+
  labs(colours="Immigration Groups")+
  theme(plot.title = element_text(hjust = 0.5),
        # legend.position = "none", 
        # panel.grid.major = element_blank(),
        # panel.grid.minor = element_blank(),
        # panel.background = element_blank(),
        axis.line = element_line(colour = "black"),
        panel.border = element_rect(colour = "black", fill=NA))+
  scale_x_discrete(limits=c(2015,2017))+ 
  scale_color_brewer(palette = "Paired")

plot_bmi <- ggplot(bmi_year, aes(x=year, y=Prevalence))+
  geom_line(aes(colour=Immigration))+
  geom_point(aes(colour=Immigration)) +
  ylab("Prevalence (%)")+
  ggtitle("Obesity")+
  xlab("Year")+
  labs(colours="Immigration Groups")+
  theme(plot.title = element_text(hjust = 0.5),
        # legend.position = "none", 
        # panel.grid.major = element_blank(), 
        # panel.grid.minor = element_blank(),
        # panel.background = element_blank(), 
        axis.line = element_line(colour = "black"),
        panel.border = element_rect(colour = "black", fill=NA))+
  scale_x_discrete(limits=c(2001,2005,2009,2013,2017))+ 
  scale_color_brewer(palette = "Paired")


plot_alc <- ggplot(alc_year, aes(x=year, y=Prevalence))+
  geom_line(aes(colour=Immigration))+
  geom_point(aes(colour=Immigration)) +
  ylab("Prevalence (%)")+
  xlab("Year")+
  ggtitle("Alcohol")+
  labs(colours="Immigration Groups")+
  theme(plot.title = element_text(hjust = 0.5),
        # legend.position = "none", 
        # panel.grid.major = element_blank(), 
        # panel.grid.minor = element_blank(),
        # panel.background = element_blank(), 
        axis.line = element_line(colour = "black"),
        panel.border = element_rect(colour = "black", fill=NA))+
  scale_x_discrete(limits=c(2001,2005,2009,2013,2017))+ 
  scale_color_brewer(palette = "Paired")

plot_smoke <- ggplot(smoke_year, aes(x=year, y=Prevalence))+
  geom_line(aes(colour=Immigration))+
  geom_point(aes(colour=Immigration)) +
  ylab("Prevalence (%)")+
  xlab("Year")+
  ggtitle("Current smoker")+
  labs(colours="Immigration Groups")+
  theme(plot.title = element_text(hjust = 0.5),
        # legend.position = "none", 
        # panel.grid.major = element_blank(), 
        # panel.grid.minor = element_blank(),
        # panel.background = element_blank(), 
        axis.line = element_line(colour = "black"),
        panel.border = element_rect(colour = "black", fill=NA))+
  scale_x_discrete(limits=c(2001,2005,2009,2013,2017))+ 
  scale_color_brewer(palette = "Paired")

plot_activity <- ggplot(activity_year, aes(x=year, y=Prevalence))+
  geom_line(aes(colour=Immigration))+
  geom_point(aes(colour=Immigration)) +
  ylab("Prevalence (%)")+
  xlab("Year")+
  ggtitle("Inactivity")+
  labs(colours="Immigration Groups")+
  theme(plot.title = element_text(hjust = 0.5),
        # legend.position = "none", 
        # panel.grid.major = element_blank(), 
        # panel.grid.minor = element_blank(),
        # panel.background = element_blank(), 
        axis.line = element_line(colour = "black"),
        panel.border = element_rect(colour = "black", fill=NA))+
  scale_x_discrete(limits=c(2001,2005,2009,2013,2017))+ 
  scale_color_brewer(palette = "Paired")

plot_rf <- ggplot(rf_year, aes(x=year, y=Prevalence))+
 geom_line(aes(colour=Immigration))+
  geom_point(aes(colour=Immigration)) +
  ylab("Prevalence (%)")+
  xlab("Year")+
  ggtitle("2+ risk factors")+
  labs(colours="Immigration Groups")+
  theme(plot.title = element_text(hjust = 0.5),
        # legend.position = "none", 
        # panel.grid.major = element_blank(), 
        # panel.grid.minor = element_blank(),
        # panel.background = element_blank(), 
        axis.line = element_line(colour = "black"),
        panel.border = element_rect(colour = "black", fill=NA))+
  scale_x_discrete(limits=c(2001,2005,2009,2013,2017))+ 
  scale_color_brewer(palette = "Paired")

plot_hd <- ggplot(hd_year, aes(x=year, y=Prevalence))+
 geom_line(aes(colour=Immigration))+
  geom_point(aes(colour=Immigration)) +
  ylab("Prevalence (%)")+
  xlab("Year")+
  ggtitle("Heart disease")+
  labs(colours="Immigration Groups")+
  theme(plot.title = element_text(hjust = 0.5),
        # legend.position = "none", 
        # panel.grid.major = element_blank(), 
        # panel.grid.minor = element_blank(),
        # panel.background = element_blank(), 
        axis.line = element_line(colour = "black"),
        panel.border = element_rect(colour = "black", fill=NA))+
  scale_x_discrete(limits=c(2001,2005,2009,2013,2017))+ 
  scale_color_brewer(palette = "Paired")

library(plotly)
ggplotly(plot_ht)
ggplotly(plot_diabetes)
ggplotly(plot_bc)
ggplotly(plot_bmi)
ggplotly(plot_alc)
ggplotly(plot_smoke)
ggplotly(plot_activity)
ggplotly(plot_rf)
ggplotly(plot_hd)
```


```{r Combined plots}
library(ggpubr)
figure2 <- ggarrange(plot_ht,plot_diabetes,plot_bc,
                     plot_bmi,plot_alc,plot_smoke,plot_activity, ncol=2, nrow=2, common.legend = TRUE)

figure2
figure_poster <- ggarrange(plot_ht,plot_diabetes,plot_bmi,plot_smoke,plot_activity, plot_rf, ncol=3, nrow=2, common.legend = TRUE)
figure_poster
```

