---
title: "4-Age-Prevalence"
author: "Kitty Chen"
date: "19/11/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Survey design and function
```{r message=FALSE, warning=FALSE}
library(srvyr)
library(dplyr)
library(tidyr)
library(survey)
library(tibble)

# Design (all)
svy_design <- as_survey_design(.data=harmonized_combined, weights="WTS_M")

# Design (male)
combined_male <- harmonized_combined %>% filter(DHH_SEX == 1)
svy_design_male <- as_survey_design(.data=combined_male, weights="WTS_M")

#Design (female)
combined_female <- harmonized_combined %>% filter(DHH_SEX == 2)
svy_design_female <- as_survey_design(.data=combined_female, weights="WTS_M")

#2011 census population standardization
pop2011 <- c(4962765,3524640,3459035,1281440,917340,4910365,3649325,3593270,1393345,1352950)
pop2011_male <-c(4962765,3524640,3459035,1281440,917340)
pop2011_female <-c(4910365,3649325,3593270,1393345,1352950)

# Prevalence
prev <- function(design, sum_var, filter_value, stdpop){
  
  # Prevalence 
  table <- svystandardize(design, by = ~Age_Group+DHH_SEX, population = stdpop)%>%
    group_by(year,Age_Group, {{sum_var}}) %>%
    summarise(Prevalence = survey_mean()*100) %>%
    filter({{sum_var}} == filter_value) %>%
    select(-Prevalence_se, -{{sum_var}})

  # Generate p-value from regression
  pval <- summary(lm(Prevalence ~ Age_Group, data = table))
  pval_col <-as.numeric(pval$coefficients[,"Pr(>|t|)"])

  # Complete table with p-value
  table1 <- table %>%
    spread(year, Prevalence) %>%
    mutate(Difference = ((`2017` - `2001`) / `2001`*100))
  table1$p_value <- pval_col
  
  table1 <- table1 %>% 
    mutate(across(everything(),round, 2)) %>%
    mutate(p_value = case_when(p_value < 0.01 ~ "< 0.01",
                               TRUE ~  as.character(p_value)))
  
  return(table1)
}

# Prevalence (blood cholesterol)
prev_bc <- function(design, sum_var, filter_value, stdpop){
  
  # Prevalence 
  table <- svystandardize(design, by = ~Age_Group+DHH_SEX, population = stdpop)%>%
    group_by(year,Age_Group, {{sum_var}}) %>%
    summarise(Prevalence = survey_mean()*100) %>%
    filter({{sum_var}} == filter_value) %>%
    select(-Prevalence_se, -{{sum_var}})

  # Generate p-value from regression
  pval <- summary(lm(Prevalence ~ Age_Group, data = table))
  pval_col <-as.numeric(pval$coefficients[,"Pr(>|t|)"])

  # Complete table with p-value
  table1 <- table %>%
    spread(year, Prevalence) %>%
    mutate(Difference = ((`2017` - `2015`) / `2015`*100))
  table1$p_value <- pval_col
  
  table1 <- table1 %>% 
    mutate(across(everything(),round, 2)) %>%
    mutate(p_value = case_when(p_value < 0.01 ~ "< 0.01",
                               TRUE ~  as.character(p_value)))
  
  # Add empty columns
  table1 <- table1 %>%
    add_column("2001" = "-", .before = "2015")%>%
    add_column("2003" = "-", .before = "2015")%>%
    add_column("2005" = "-", .before = "2015")%>%
    add_column("2007" = "-", .before = "2015")%>%
    add_column("2009" = "-", .before = "2015")%>%
    add_column("2011" = "-", .before = "2015")%>%
    add_column("2013" = "-", .before = "2015") 
  
  return(table1)
}

```

## Both sex

```{r Hypertension}
ht_t1 <-prev(svy_design, CCC_071, 1, pop2011)
ht_t1 
```

```{r Diabetes}
db_t1 <-prev(svy_design, CCC_101, 1, pop2011)
db_t1
```

```{r Blood cholesterol}
bc_t1 <-prev_bc(svy_design, CCC_075, 1, pop2011)
bc_t1
```

```{r Obesity}
bmi_t1 <-prev(svy_design, HWTGBMI_der_cat4, 4, pop2011)
bmi_t1
```

```{r Physical inactivity}
mets_t1 <- prev(svy_design, activity, "Inactive", pop2011)
mets_t1
```

```{r Smoking}
smoke_t1 <- prev(svy_design, SMKDSTY_cat3, 1, pop2011)
smoke_t1
```

```{r Drinking}
alc_t1 <-prev(svy_design, Alcohol, 4, pop2011)
alc_t1
```

```{r Full table}
# Tb_t1 <- gtsummary::tbl_stack(list(alc_tb, bmi_tb,db_tb,ht_tb, mets_tb,smoke_tb, pop2011), pop2011)

```

## Male

```{r Hypertension}
ht_t1_m <-prev(svy_design_male, CCC_071, 1, pop2011_male)
ht_t1_m 
```

```{r Diabetes}
db_t1_m <-prev(svy_design_male, CCC_101, 1, pop2011_male)
db_t1_m
```

```{r Blood cholesterol}
bc_t1_m <-prev_bc(svy_design_male, CCC_075, 1, pop2011_male)
bc_t1_m
```

```{r Obesity}
bmi_t1_m <-prev(svy_design_male, HWTGBMI_der_cat4, 4, pop2011_male)
bmi_t1_m
```

```{r Physical inactivity}
mets_t1_m <- prev(svy_design_male, activity, "Inactive", pop2011_male)
mets_t1_m
```

```{r Smoking}
smoke_t1_m <- prev(svy_design_male, SMKDSTY_cat3, 1, pop2011_male)
smoke_t1_m
```

```{r Drinking}
alc_t1_m <-prev(svy_design_male, Alcohol, 4, pop2011_male)
alc_t1_m
```

```{r Full table}
# Tb_t1_m <- gtsummary::tbl_stack(list(alc_tb, bmi_tb,db_tb,ht_tb, mets_tb,smoke_tb, pop2011), pop2011)

```

## Female

```{r Hypertension}
ht_t1_f <-prev(svy_design_female, CCC_071, 1, pop2011_female)
ht_t1_f 
```

```{r Diabetes}
db_t1_f <-prev(svy_design_female, CCC_101, 1, pop2011_female)
db_t1_f
```

```{r Blood cholesterol}
bc_t1_f <-prev_bc(svy_design_female, CCC_075, 1, pop2011_female)
bc_t1_f
```

```{r Obesity}
bmi_t1_f <-prev(svy_design_female, HWTGBMI_der_cat4, 4, pop2011_female)
bmi_t1_f
```

```{r Physical inactivity}
mets_t1_f <- prev(svy_design_female, activity, "Inactive", pop2011_female)
mets_t1_f
```

```{r Smoking}
smoke_t1_f <- prev(svy_design_female, SMKDSTY_cat3, 1, pop2011_female)
smoke_t1_f
```

```{r Drinking}
alc_t1_f <-prev(svy_design_female, Alcohol, 4, pop2011_female)
alc_t1_f
```

```{r}
library(huxtable)
hux<- function(risk, riskm, riskf, title){
  all <- rbind(risk, riskm, riskf)
  
  all_hux <- as_hux(all) %>%
    theme_article()%>%
    insert_row(c("Both", "","","","","","","","","","",""),after = 1) %>%
    insert_row(c("Male", "","","","","","","","","","",""),after = 7) %>%
    insert_row(c("Female", "","","","","","","","","","",""),after = 12) %>%
    set_italic(2,1)%>%
    set_italic(8,1)%>%
    set_italic(13,1)%>%
    set_bottom_border( row = 7) %>%
    insert_row(c(title, "","","","","","","","","","",""),after = 1)
  
  return(all_hux)
}
all_ht_hux <- hux(ht_t1, ht_t1_m, ht_t1_f, "Hypertension")
all_db_hux <- hux(db_t1, db_t1_m, db_t1_f, "Diabetes")
all_bc_hux <- hux(bc_t1, bc_t1_m, bc_t1_f, "High blood cholesterol")
all_bmi_hux <- hux(bmi_t1, bmi_t1_m, bmi_t1_f, "Obesity")
all_mets_hux <- hux(mets_t1, mets_t1_m, mets_t1_f,"Physical inactivity")
all_smoke_hux <- hux(smoke_t1, smoke_t1_m, smoke_t1_f,"Current smoker")
all_alc_hux <- hux(alc_t1, alc_t1_m, alc_t1_f,"Heavy drinker")

cbind.huxtable(all_ht_hux, all_db_hux[-2])
```

```{r Full table}
# Tb_t1_f <- gtsummary::tbl_stack(list(alc_tb, bmi_tb,db_tb,ht_tb, mets_tb,smoke_tb))
library(gt)
years <- c("2001", "2003", "2005", "2007", "2009", "2011", "2013", "2015", "2017")

all_t1 <- rbind(ht_t1, db_t1, bmi_t1, mets_t1, smoke_t1, alc_t1,
                ht_t1_m, db_t1_m, bmi_t1_m, mets_t1_m, smoke_t1_m, alc_t1_m,
                ht_t1_f, db_t1_f, bmi_t1_f, mets_t1_f, smoke_t1_f, alc_t1_f)
all_t1_gt <- gt(tibble(all_t1)) %>%
  tab_spanner(label ="Year; prevalence, %",
              columns = years) %>%
  # Sex
  tab_row_group(label = "Female", rows =61:90) %>%
  tab_row_group(label = "Male", rows = 31:60) %>%
  tab_row_group(label = "Both", rows = 1:30)%>%
  tab_style(style = cell_text(weight = "bold"), locations = list(cells_row_groups())) %>%
  
  # Characteristics
  tab_row_group(label = "Heavy drinker (F)", rows = 86:90)%>%
  tab_row_group(label = "Current smoker (F)", rows = 81:85)%>%
  tab_row_group(label = "Physical inactivity (F)", rows = 76:80)%>%
  tab_row_group(label = "Obesity (F)", rows = 71:75)%>%
  tab_row_group(label = "Diabetes (F)", rows = 66:70)%>%
  tab_row_group(label = "Hypertension (F)", rows = 61:65)%>%
  
  tab_row_group(label = "Heavy drinker (M)", rows = 56:60)%>%
  tab_row_group(label = "Current smoker (M)", rows = 51:55)%>%
  tab_row_group(label = "Physical inactivity (M)", rows = 46:50)%>%
  tab_row_group(label = "Obesity (M)", rows = 41:45)%>%
  tab_row_group(label = "Diabetes (M)", rows = 36:40)%>%
  tab_row_group(label = "Hypertension (M)", rows = 31:35)%>%
  
  tab_row_group(label = "Heavy drinker", rows = 26:30)%>%
  tab_row_group(label = "Current smoker", rows = 21:22)%>%
  tab_row_group(label = "Physical inactivity", rows = 16:20)%>%
  tab_row_group(label = "Obesity", rows = 11:15)%>%
  tab_row_group(label = "Diabetes", rows = 6:10)%>%
  tab_row_group(label = "Hypertension", rows = 1:5)%>%
  
  tab_style(style = cell_text(weight = "bold"), locations = list(cells_row_groups())) %>%
  cols_label(p_value = "p-value",
             Difference = "Relative change, %")

as_raw_html(all_t1_gt)
```


