---
title: "2+ Risk Factors"
author: "Kitty Chen"
# date: 2023-02-06
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Survey design and function
```{r}
library(srvyr)
library(dplyr)
library(tidyr)
library(survey)
library(huxtable)


# Design for 2001-2014
harmonized_2001_2014 <- harmonized_combined[!(harmonized_combined$year==2015|harmonized_combined$year==2017),]
svy_design <- srvyr::as_survey_design(.data=harmonized_2001_2014, weights="WTS_M")

#2011 census population standardization (age and sex)
pop2011 <- c(4962765,3524640,3459035,1281440,917340,4910365,3649325,3593270,1393345,1352950)

# Prevalence for 2+ risk factors by migrant group
prev_imm <- function(design, design_bsw, sum_var, filter_value, stdpop){
  
  # Prevalence for 2000-2014
  table_non_bsw <- svystandardize(design, by = ~Age_Group+DHH_SEX, 
                                  population = stdpop)%>%
    group_by(year, Immigration, {{sum_var}}) %>%
    summarise(Prevalence = round(survey_mean(vartype = "ci")*100, 2)) %>%
    filter({{sum_var}} == filter_value) %>%
    select(-{{sum_var}})
  
  # Prevalence for bsw in 2015-2018
  table_bsw <- svystandardize(design_bsw, by = ~Age_Group+DHH_SEX, 
                              population = stdpop)%>%
    group_by(year, Immigration, {{sum_var}}) %>%
    summarise(Prevalence = round(survey_mean(vartype = "ci")*100, 2)) %>%
    filter({{sum_var}} == filter_value) %>%
    select(-{{sum_var}})
  
  # Combine table
  table_ci <- bind_rows(table_non_bsw, table_bsw)
  
  # Combined table without confidence interval
  table <- table_ci[,-c(4,5)]
  
  # Generate p-value from regression
  pval <- summary(lm(Prevalence ~ Immigration, data = table))
  pval_col <-as.numeric(pval$coefficients[,"Pr(>|t|)"])
  
  # Complete table with difference
  table1 <- table %>%
    spread(year, Prevalence) %>%
    mutate(Difference = ((`2017` - `2001`) / `2001`*100))
  
  table1$p_value <- pval_col
  
  table1 <- table1 %>% 
    mutate(across(everything(),round, 2)) %>%
    mutate(p_value = case_when(p_value < 0.01 ~ "< 0.01",
                               TRUE ~  as.character(p_value)))
  
  # Add CI to final table
  table_ci$Prevalence_CI <-paste0(table_ci$Prevalence, " (", 
                                  table_ci$Prevalence_low,",", 
                                  table_ci$Prevalence_upp, ")")
  table_ci <- table_ci[,-c(3:5)]
  table_ci <- table_ci %>%
    spread(year, Prevalence_CI)
  table_ci$Difference <- table1$Difference
  table_ci$p_value <- table1$p_value
  
  return(table_ci)
}
```

## Final table
```{r 2+ risk factors}
rf2 <- prev_imm(svy_design, svy_design_2015_2018, Risk_factor, "2+", pop2011)

rf2_df <- as.data.frame(rf2)
all_rf_final <- as_hux(rf2_df) %>%
  theme_article()%>%
  set_top_border()
print(all_rf_final)
```

