---
title: "Table2-Descriptive-Statistics"
author: Kitty Chen
date: 2024-05-27
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Labels
```{r Factoring each variable, message=FALSE, warning=FALSE, include=FALSE}
library(dplyr)

source("R/harmonized_data.R")

T1 <- harmonized_combined

# Sex
T1$DHH_SEX <-
  factor(T1$DHH_SEX, levels=c(1,2),
         labels=c('Male','Female'))
levels(T1$DHH_SEX)

# Province
T1$Province <- as.factor(T1$Province)
levels(T1$Province)

# Immigrant group
T1$Immigration<- as.factor(T1$Immigration)
levels(T1$Immigration)

# BMI
T1$HWTGBMI_der_cat4<- 
  factor(T1$HWTGBMI_der_cat4, levels = c(1:4),
         labels=c('Underweight','Normal weight','Overweight','Obese'))
levels(T1$HWTGBMI_der_cat4)

# Hypertension
T1$CCC_071 <-
  factor(T1$CCC_071, levels=c(1,2),
         labels=c('Hypertension','No hypertension'))
levels(T1$CCC_071)

# Diabetes
T1$CCC_101 <-
  factor(T1$CCC_101, levels=c(1,2),
         labels=c('Diabetes','No diabetes'))
levels(T1$CCC_101)

# Blood cholesterol
T1$CCC_075 <-
  factor(T1$CCC_075, levels=c(1,2),
         labels=c('High blood cholesterol','No high blood cholesterol'))
levels(T1$CCC_075)

# Drinking
T1$Alcohol <-
  factor(T1$Alcohol, levels=c(1:4),
         labels=c('Non-drinker', 'Light drinker', 'Moderate drinker','Heavy drinker'))
levels(T1$Alcohol)

# Smoking
T1$SMKDSTY_cat3 <-
  factor(T1$SMKDSTY_cat3, levels=c(1:3),
         labels=c('Current smoker', 'Former smoker', 'Never smoked'))
levels(T1$SMKDSTY_cat3)

# Activity
T1$activity <- as.factor(T1$activity)
levels(T1$activity)

# Year
T1$year <- as.factor(T1$year)
levels(T1$year)

# Province
T1$Province <- as.factor(T1$Province)
levels(T1$Province)

# Age
T1$Age_Group <- as.factor(T1$Age_Group)
levels(T1$Age_Group)

# Number of risk factors
T1$Risk_factor <- as.factor(T1$Risk_factor)
levels(T1$Risk_factor)

# Heart disease
T1$CCC_121 <- factor(T1$CCC_121, levels=c(1,2),
         labels=c('Heart disease','No heart disease'))
levels(T1$CCC_121)
```

```{r Rename titles, message=FALSE, warning=FALSE}
T1 <- T1 %>%
  select(Age_Group, DHH_SEX,Province, year,Immigration,CCC_121, HWTGBMI_der_cat4,CCC_071,CCC_075,
         CCC_101,Alcohol,SMKDSTY_cat3,activity, Risk_factor, WTS_M) %>%
  rename('Age'=Age_Group,'Sex'=DHH_SEX, 'Body Mass Index (BMI)'=HWTGBMI_der_cat4,
         'Leisure activity'=activity,'Hypertension'=CCC_071,'Blood cholesterol'=CCC_075,
         'Diabetes'=CCC_101,'Smoking status'=SMKDSTY_cat3, "Year"=year, 'Number of risk factors'= Risk_factor, 
         'Heart disease'=CCC_121)
colnames(T1)
```

## Final table
```{r Table 1 stratified by sex (weight and unweighted)}
T1_unweighted <- T1%>%
  select(-WTS_M)

t1_unweighted <- gtsummary::tbl_summary(data=T1_unweighted, 
                                        by='Sex',
                                        digits = 2,
                                        missing = "no")

t1_design <- survey::svydesign(id=~0, weights=~WTS_M, data=T1)

t1_weighted <-gtsummary::tbl_svysummary(data =t1_design, 
                                        by = 'Sex',
                                        digits = 2,
                                        missing = "no")

t1_sex<-gtsummary::tbl_merge(tbls = list(t1_unweighted, t1_weighted),
          tab_spanner=c("**Unweighted**","**Weighted**"))

t1_sex_final<-print(t1_sex)

# Print out final table 
t1_sex %>%
  gtsummary::as_hux_table()%>%
  quick_xlsx(file = "Table2-Descriptive.xlsx")
```